import "@/styles/configuracion.css";
import Link from "next/link";

export const metadata = {
    title: "[NeuralNode];",
    description: "Generated by create next app"
};


export default function Nosotros() {
    return (
        <main>
            <div id="fondo-main">
                <h2>Nuestra informacion <i className="fa-solid fa-child-reaching"></i></h2>
            </div>

            <div className="padre-novedades">
                <div className="hijo-novedades">
                    <h4>Historia</h4>
                    <p>Iniciamos en el año 2020 en pandemia. Queriamos realizar una pagina que brinde informacion en
                        general,
                        sobre informatica. Todo lo que se relacione con ella.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem voluptate aliquam quas quibusdam corporis blanditiis harum, numquam eligendi illo odit, reprehenderit obcaecati eos voluptates accusamus. Excepturi libero at sit corporis!</p>
                    <p>Es por ello que nos gustaria que cualquier idea o critica que tengas, para sumar y ser parte de esta
                        comunidad, nos los hagas saber a continuacion, <b>dejando tus datos y breve mensaje.</b>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos hic cum quos nam debitis numquam neque cumque distinctio enim voluptates officia doloribus, laborum dicta nostrum accusantium tenetur ad quaerat corporis!</p>
                    
                </div>
                <form action="" method="" className="formulario">
                <p>
                    <label htmlFor="nombre">Nombre</label>
                    <input type="text" name="" placeholder="Asi sabremos quien escribe =)" />
                </p>
                <p>
                    <label htmlFor="email">Mail</label>
                    <input type="text" name="" placeholder="Con este mail nos contactaremos" />
                </p>
                <p>
                    <label htmlFor="mensaje">Mensaje</label>
                    <textarea name="" placeholder="Aqui escriba su mensaje"></textarea>
                </p>
                <p>
                    <input type="submit" value="Enviar" />
                </p>
            </form>
            </div>
        </main>
    )
};