import "@/styles/configuracion.css";
import Link from "next/link"


export const metadata = {
    title: "[NeuralNode];",
    description: "Generated by create next app"
};


export default function Software() {
    return (
        <main>
        <div id="fondo-main">
            <h2>Software <i className="fa-solid fa-file"></i></h2>
        </div>
        <div className="ContainerSoft">
            <div className="CajasHijas">
                <ol>
                    <h4>Software para navegadores</h4>
                    <li>
                        <div>
                            <p>Google Chrome</p><Link href="https://www.google.com/intl/es-419/chrome/"><img
                                    src="https://play-lh.googleusercontent.com/QRRGW2tMZ4-FNw0XWk6WWiXHaQCGxuwM-92HrBhlA4WOd_AGmjVmQkiHyAqQjW2yByc"
                                     /></Link>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>EDGE</p><Link href="https://www.microsoft.com/es-es/edge/download?form=MA13FJ"><img
                                    src="https://img.utdstc.com/icon/c61/f16/c61f16d6194ccd61a56256494fb870b9606afbce00b8fa2e0551d5ffaad0389f:200"
                                     /></Link>
                        </div>
                    </li>
                </ol>
            </div>
            <div className="CajasHijas">
                <ol>
                    <h4>Software para seguridad</h4>
                    <li>
                        <div>
                            <p>McAfee</p><Link href="https://www.mcafee.com/"><img
                                    src="https://www.mcafee.com/blogs/wp-content/uploads/2017/05/Social-Media-PF-Logo-Pic.jpg"
                                     /></Link>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>Avast</p><Link href="https://www.avast.com/es-ar/index"><img
                                    src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRncS00xMgnzzgjPDpL6U5EIuzAthPhX_DpmA&s"
                                     /></Link>
                        </div>
                    </li>
                </ol>
            </div>
            <div className="CajasHijas">
                <ol>
                    <h4>Software para programación</h4>
                    <li>
                        <div>
                            <p>Visual Studio Code</p><Link href="https://code.visualstudio.com/"><img
                                    src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn91uTL21JJpJN1JrzGYppRDxj9vKzk0fpKA&s"
                                     /></Link>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>PyCharm</p><Link href="https://www.jetbrains.com/es-es/pycharm/download/"><img
                                    src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBZtTslgnfHa3O43RSPNIEJgYugJ92XI1fPQ&s"
                                     /></Link>
                        </div>
                    </li>
                </ol>
            </div>
            <div className="CajasHijas">
                <ol>
                    <h4>Software para diseño gráfico</h4>
                    <li>
                        <div>
                            <p>Figma</p><Link href="https://www.figma.com/"><img
                                    src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSx5iiElHMD2Hbxg4sydEIbLgbd3cnOiYgzmg&s"
                                     /></Link>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>Adobe Photoshop</p><Link href="https://www.adobe.com/es/products/photoshop.html"><img
                                    src="https://1000marcas.net/wp-content/uploads/2020/01/Photoshop-Logo-2019.jpg"
                                     /></Link>
                        </div>
                    </li>
                </ol>
            </div>
        </div>
    </main>
    )

};