import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/configuracion.css";

export const metadata = {
  title: "[NeuralNode];",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>
            <h1><a href="/">[NeuralNode];</a></h1>
          </div>
          <p>Centro neurálgico del conocimiento digital, libre para todos.</p>
        </header>

        <Nav />

        {children}


        <Footer />
      </body>
    </html>
  );
}
