import Link from "next/link";
import "@/styles/configuracion.css";

export const metadata = {
  title: "[NeuralNode];",
  description: "Generated by create next app",
};

const Hardware = (props) => {
    return (
        <main>
            <div id="fondo-main">
                <h2>Informacion sobre hardware <i className="fa-solid fa-memory"></i></h2>
            </div>
            <div className="row caja-padre-hard">

                <div className="col-6 col-md-2 caja-hijo-hard">
                    <div className="card text-center mt-3" >
                        <img src="https://static.vecteezy.com/system/resources/previews/004/495/458/non_2x/video-card-line-icon-free-vector.jpg"
                             className="jpg" alt="jpg" />
                            <div className="card-body ">
                                <h5 className="card-title">Placa de video</h5>
                                <p className="card-text">También conocida como GPU o tarjeta gráfica, se encarga de procesar la
                                    información visual para mostrarla en un monitor.</p>
                                <Link href="https://www.xataka.com/basics/tarjeta-grafica-que-que-hay-dentro-como-funciona"
                                    target="_blank" className="btn btn-primary">Ver info</Link>
                            </div>
                    </div>
                </div>
                <div className="col-6 col-md-2 caja-hijo-hard">
                    <div className="card text-center my-3" >
                        <img src="https://img.freepik.com/vector-gratis/ilustracion-disco-duro-dibujado-mano_23-2149388655.jpg?semt=ais_hybrid&w=740"
                             className="jpg" alt="jpg" />
                            <div className="card-body ">
                                <h5 className="card-title">Almacenamiento</h5>
                                <p className="card-text">Puede ser HDD, SSD, NVME ... Todos son unidades de almacenamiento.</p>
                                <Link href="https://www.hpe.com/lamerica/es/what-is/data-storage.html#:~:text=El%20almacenamiento%20de%20datos%20consiste,accesibles%20siempre%20que%20sean%20necesarios."
                                    target="_blank" className="btn btn-primary">Ver info</Link>
                            </div>
                    </div>
                </div>
                <div className="col-6 col-md-2 caja-hijo-hard">
                    <div className="card text-center my-3" >
                        <img src="https://cdn-icons-png.flaticon.com/512/1470/1470179.png"  className="jpg"
                            alt="jpg" />
                            <div className="card-body ">
                                <h5 className="card-title">Fuente de poder</h5>
                                <p className="card-text">Es el hardware mas importante en nuestro ordenador. Es la fuente de
                                    alimentacion. Sin ella nada funcionaria.</p>
                                <Link href="https://www.corsair.com/es/es/explorer/diy-builder/power-supply-units/what-is-a-psu-power-supply-units-explained/?srsltid=AfmBOooazTQP0kuOONOL0C6AGjSjBAc7tMHwBBUXVYyY9xaZSVm9Jhoc"
                                    target="_blank" className="btn btn-primary">Ver info</Link>
                            </div>
                    </div>
                </div>
                <div className="col-6 col-md-2 caja-hijo-hard">
                    <div className="card text-center my-3" >
                        <img src="https://static.vecteezy.com/system/resources/previews/006/065/039/non_2x/smiling-processor-linear-icon-well-working-microprocessor-thin-line-illustration-chip-microchip-chipset-in-good-quality-cpu-integrated-circuit-isolated-outline-drawing-editable-stroke-vector.jpg"
                             className="jpg" alt="jpg" />
                            <div className="card-body">
                                <h5 className="card-title">Microprocesador</h5>
                                <p className="card-text">Procesa los datos de todo el ordenador.</p>
                                <Link href="https://www.pccomponentes.com/que-es-un-microprocesador-cual-es-su-funcion?srsltid=AfmBOoqfhRib1fuk2VV4sL3jqCA5s8xVn7x1o9_Zzwi5xsc18CHbYd2u"
                                    target="_blank" className="btn btn-primary">Ver info</Link>
                            </div>
                    </div>
                </div>
                <div className="col-6 col-md-2 caja-hijo-hard">
                    <div className="card text-center my-3" >
                        <img src="https://cdn-icons-png.freepik.com/512/7209/7209481.png"  className="jpg"
                            alt="jpg" />
                            <div className="card-body">
                                <h5 className="card-title">Memoria RAM</h5>
                                <p className="card-text">Encargado de brindar memoria para tener precargado y tenerlo listo lo que
                                    vaya a ejecutar el Microprocesador .</p>
                                <Link href="https://www.xataka.com/basics/memoria-ram-que-sirve-como-mirar-cuanta-tiene-tu-ordenador-movil"
                                    target="_blank" className="btn btn-primary">Ver info</Link>
                            </div>
                    </div>
                </div>
                <div className="col-6 col-md-2 caja-hijo-hard">
                    <div className="card text-center my-3" >
                        <img src="https://cdn.pixabay.com/photo/2015/03/21/06/28/motherboard-683247_1280.png"
                             className="jpg" alt="jpg" />
                            <div className="card-body">
                                <h5 className="card-title">Motherboard</h5>
                                <p className="card-text">La placa madre se encarga de comunicar un componente con otro.</p>
                                <Link href="https://compubit.com.co/que-es-una-motherboard-y-para-que-funciona/?srsltid=AfmBOoqk3L2iVbshARfjan6xrDQwmwJhtzNLIi28QoUe82yRq4k4XT5S"
                                    target="_blank" className="btn btn-primary">Ver info</Link>
                            </div>
                    </div>
                </div>
            </div>
        </main>
    )
};


export default Hardware;